Sourcing minigraphs...
Traceback (most recent call last):
  File "/mnt/ufs18/home-245/martjor/repos/dev_pt/batch/../src/miniaturize.py", line 15, in <module>
Traceback (most recent call last):
Traceback (most recent call last):
  File "/mnt/ufs18/home-245/martjor/repos/dev_pt/batch/../src/miniaturize.py", line 15, in <module>
Traceback (most recent call last):
  File "/mnt/ufs18/home-245/martjor/repos/dev_pt/batch/../src/miniaturize.py", line 15, in <module>
Traceback (most recent call last):
  File "/mnt/ufs18/home-245/martjor/repos/dev_pt/batch/../src/miniaturize.py", line 15, in <module>
  File "/mnt/ufs18/home-245/martjor/repos/dev_pt/batch/../src/miniaturize.py", line 15, in <module>
    from mpi4py import MPI
ModuleNotFoundError: No module named 'mpi4py'
    from mpi4py import MPI
ModuleNotFoundError: No module named 'mpi4py'
    from mpi4py import MPI
ModuleNotFoundError: No module named 'mpi4py'
    from mpi4py import MPI
ModuleNotFoundError: No module named 'mpi4py'
Traceback (most recent call last):
  File "/mnt/ufs18/home-245/martjor/repos/dev_pt/batch/../src/miniaturize.py", line 15, in <module>
    from mpi4py import MPI
ModuleNotFoundError: No module named 'mpi4py'
    from mpi4py import MPI
ModuleNotFoundError: No module named 'mpi4py'
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpiexec detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[32976,1],1]
  Exit code:    1
--------------------------------------------------------------------------
